-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES Table
create table public.profiles (
  id uuid not null references auth.users(id) on delete cascade primary key,
  email text,
  nickname text,
  avatar_url text,
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

-- 2. USER SETTINGS Table
create table public.user_settings (
    user_id uuid not null references public.profiles(id) on delete cascade primary key,
    theme text default 'light',
    font_size text default 'medium',
    auto_sharing boolean default false,
    share_time time, -- HH:MM:00
    preferred_translation text default 'krv', -- krv, niv, nlt
    updated_at timestamptz default now()
);

alter table public.user_settings enable row level security;

create policy "Users can view their own settings" on public.user_settings
  for select using (auth.uid() = user_id);

create policy "Users can insert their own settings" on public.user_settings
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own settings" on public.user_settings
  for update using (auth.uid() = user_id);

-- 3. USER READINGS Table (Bible Reading History)
create table public.user_readings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    plan_id integer not null, -- References local BibleReadingPlan ID
    completed_at timestamptz default now(),
    platform text default 'web', -- 'web', 'app', 'widget'
    unique(user_id, plan_id) -- Prevent duplicate readings for same plan
);

alter table public.user_readings enable row level security;

create policy "Users can view their own readings" on public.user_readings
  for select using (auth.uid() = user_id);

create policy "Users can insert their own readings" on public.user_readings
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own readings" on public.user_readings
  for delete using (auth.uid() = user_id);

-- 4. JOURNAL ENTRIES Table (Meditations)
create table public.journal_entries (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    plan_id integer, -- Optional link to a reading plan
    content text not null,
    mood text,
    ai_feedback jsonb, -- Structured AI response
    tags text[],
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

alter table public.journal_entries enable row level security;

create policy "Users can view their own journals" on public.journal_entries
  for select using (auth.uid() = user_id);

create policy "Users can insert their own journals" on public.journal_entries
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own journals" on public.journal_entries
  for update using (auth.uid() = user_id);

create policy "Users can delete their own journals" on public.journal_entries
  for delete using (auth.uid() = user_id);

-- 5. Functions & Triggers

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, nickname)
  values (new.id, new.email, split_part(new.email, '@', 1));
  
  insert into public.user_settings (user_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call handle_new_user
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
