-- Migration: Covenant Squads Setup

-- 1. Groups Table (If not using just messaging based)
CREATE TABLE IF NOT EXISTS public.groups (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    invite_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    theme TEXT DEFAULT 'default', -- e.g., 'dawn', 'fire', 'forest'
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by UUID REFERENCES auth.users(id)
);

-- 2. Group Members (For tracking history/stats beyond realtime)
CREATE TABLE IF NOT EXISTS public.group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id TEXT NOT NULL, -- references groups(invite_code) or id
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    role TEXT DEFAULT 'member', -- 'leader', 'member'
    joined_at TIMESTAMPTZ DEFAULT now(),
    last_read_at TIMESTAMPTZ,
    streak INTEGER DEFAULT 0,
    
    UNIQUE(group_id, user_id)
);

-- 3. Enhanced Messages (Using existing group_messages or new table)
-- If using existing `group_messages`, ensure `type` column exists and text is flexible.
-- ALTER TABLE public.group_messages ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'chat';
-- ALTER TABLE public.group_messages ADD COLUMN IF NOT EXISTS payload JSONB;

-- 4. Realtime Policies
-- Ensure Realtime is enabled for these tables in Supabase Dashboard.
-- bucket: 'avatars' (if used)

-- 5. Row Level Security (RLS)
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view groups they know the code of" 
ON public.groups FOR SELECT 
USING (true); -- Or clearer logic: invite_code is public knowledge if shared

CREATE POLICY "Members can view other members"
ON public.group_members FOR SELECT
USING (true);

CREATE POLICY "Users can join"
ON public.group_members FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Enable Realtime
-- publication: supabase_realtime
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.groups, public.group_members;
